name = "MachineElements"
uuid = "67c58264-06e4-44db-9737-f1b0a92351b2"
authors = ["Rojesh Man Shikhrakar"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
